FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Md. Golam Maula Maruf
RESTful API using mongodb.

**Dependencies**
`Framework:` **Java Spring Framework**

`Database` **Mongodb**

##Cell No Collection [/cell]

### CELL NO [GET]
+ Response 200 (application/json)

        {
            name: "Sheikh Hasina"
            cell: "+88 017 11223344"

            name: "Khaledia Zia"
            cell: "+88 017 44332211"

            name: "Hossain Md. Ershad" 
            cell: "+88 017 14420420"
        }